name: CI
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - master
      - develop
    paths:
      - 'cli/**'
      - 'runtime/**'
      - 'demo-apps/**'
      - 'package.json'
      - 'yarn.lock'
      - '.github/workflows/ci.yml'
  push:
    paths:
      - 'cli/**'
      - 'runtime/**'
      - 'demo-apps/**'
      - 'package.json'
      - 'yarn.lock'
      - 'scripts/release/**'
      - '.github/workflows/ci.yml'
    branches:
      - '*'
      - '**'
      - '!master'
      - '!develop'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  CI:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      contents: read

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn

      - name: Yarn
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          yarn install --frozen-lockfile --ignore-scripts
          yarn buildall
          yarn test

      - name: Disable AppArmor
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

      - name: Build and Test Demo APP
        run: |
          ./demo-apps/build-and-test.sh
