name: CI
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - master
      - develop
    paths:
      - 'cli/**'
      - 'runtime/**'
      - 'demo-apps/**'
      - 'scripts/release/**'
      - 'package.json'
      - 'bun.lock'
      - '.releaserc.json'
      - '.github/workflows/ci.yml'
      - '.github/workflows/release.yml'
  push:
    paths:
      - 'cli/**'
      - 'runtime/**'
      - 'demo-apps/**'
      - 'package.json'
      - 'bun.lock'
      - 'scripts/release/**'
      - '.github/workflows/ci.yml'
      - '.github/workflows/release.yml'
      - '.releaserc.json'
    branches:
      - '*'
      - '**'
      - '!master'
      - '!develop'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  CI:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      contents: read

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.14

      - name: Bun
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          bun ci
          bun run buildall
          bun run test

      - name: Disable AppArmor
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

      - name: Build and Test Demo APP
        run: |
          ./demo-apps/build-and-test.sh
